apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5134
          - path: /file(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: file-service
                port:
                  number: 5057
          - path: /report(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: report-service
                port:
                  number: 5103
          - path: /search(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: search-service
                port:
                  number: 5248
